"""
Curated Seed Registry of Top Tech Companies & Unicorns on Greenhouse ATS
"""

GREENHOUSE_SEED_COMPANIES = [
    {"name": "Groww", "slug": "groww"},
    {"name": "Pine Labs", "slug": "pine"},
    {"name": "Stripe", "slug": "stripe"},
    {"name": "Figma", "slug": "figma"},
    {"name": "Airbnb", "slug": "airbnb"},
    {"name": "Vercel", "slug": "vercel"},
    {"name": "Datadog", "slug": "datadog"},
    {"name": "Cloudflare", "slug": "cloudflare"},
    {"name": "GitHub", "slug": "github"},
    {"name": "DoorDash", "slug": "doordash"},
    {"name": "Reddit", "slug": "reddit"},
    {"name": "Pinterest", "slug": "pinterest"},
    {"name": "Discord", "slug": "discord"},
    {"name": "Dropbox", "slug": "dropbox"},
    {"name": "Coinbase", "slug": "coinbase"},
    {"name": "Gusto", "slug": "gusto"},
    {"name": "Instacart", "slug": "instacart"},
    {"name": "Lyft", "slug": "lyft"},
    {"name": "Robinhood", "slug": "robinhood"},
    {"name": "MongoDB", "slug": "mongodb"},
    {"name": "Brex", "slug": "brex"},
    {"name": "HashiCorp", "slug": "hashicorp"},
    {"name": "PagerDuty", "slug": "pagerduty"},
    {"name": "Twilio", "slug": "twilio"},
    {"name": "Scale AI", "slug": "scaleai"},
    {"name": "Checkr", "slug": "checkr"},
    {"name": "Zapier", "slug": "zapier"},
    {"name": "GitLab", "slug": "gitlab"},
    {"name": "Snap", "slug": "snap"},
    {"name": "Square / Block", "slug": "block"},
    {"name": "Samsara", "slug": "samsara"},
    {"name": "slice", "slug": "slice"},
    {"name": "HighRadius", "slug": "highradius"},
    {"name": "Zenoti", "slug": "zenoti"},
    {"name": "Druva", "slug": "druva"},
    {"name": "Porter", "slug": "porter"},
    {"name": "InMobi", "slug": "inmobi"},
    {"name": "Glance", "slug": "glance"},
    {"name": "Tata Consultancy Services", "slug": "tcs"},
    {"name": "Databricks", "slug": "databricks"},
    {"name": "Elastic", "slug": "elastic"},
    {"name": "Oliver Wyman", "slug": "oliver"},
    {"name": "Boston Consulting Group", "slug": "bcg"},
]
