"""
Master directory of 300+ Indian tech companies, unicorns, startups, MNC GCCs,
and IT services employers for ATS board discovery.
"""

from typing import List, Dict, Any

INDIAN_COMPANIES: List[Dict[str, Any]] = [
    # ── E-Commerce, Quick-Commerce & Retail Tech ──
    {"name": "Flipkart", "slug_hints": ["flipkart"]},
    {"name": "Swiggy", "slug_hints": ["swiggy"]},
    {"name": "Zomato", "slug_hints": ["zomato"]},
    {"name": "Zepto", "slug_hints": ["zepto", "zeptocook"]},
    {"name": "Blinkit", "slug_hints": ["blinkit", "grofers"]},
    {"name": "Meesho", "slug_hints": ["meesho"]},
    {"name": "Nykaa", "slug_hints": ["nykaa", "fsn-ecommerce"]},
    {"name": "BigBasket", "slug_hints": ["bigbasket", "innovative-retail"]},
    {"name": "Licious", "slug_hints": ["licious", "delightful-gourmet"]},
    {"name": "Purplle", "slug_hints": ["purplle"]},
    {"name": "Country Delight", "slug_hints": ["countrydelight", "country-delight"]},
    {"name": "DealShare", "slug_hints": ["dealshare"]},
    {"name": "CityMall", "slug_hints": ["citymall"]},
    {"name": "Snapdeal", "slug_hints": ["snapdeal"]},

    # ── Fintech, Payments & Wealthtech ──
    {"name": "Razorpay", "slug_hints": ["razorpay"]},
    {"name": "PhonePe", "slug_hints": ["phonepe"]},
    {"name": "Paytm", "slug_hints": ["paytm", "one97"]},
    {"name": "CRED", "slug_hints": ["cred", "dreamplug"]},
    {"name": "Groww", "slug_hints": ["groww", "nextbillion-technology"]},
    {"name": "Zerodha", "slug_hints": ["zerodha"]},
    {"name": "Pine Labs", "slug_hints": ["pinelabs", "pine-labs"]},
    {"name": "BharatPe", "slug_hints": ["bharatpe", "resilient-innovations"]},
    {"name": "Upstox", "slug_hints": ["upstox", "rksv"]},
    {"name": "Cashfree Payments", "slug_hints": ["cashfree", "cashfree-payments"]},
    {"name": "Navi Technologies", "slug_hints": ["navi", "navi-technologies"]},
    {"name": "Jupiter Money", "slug_hints": ["jupiter", "jupiter-money", "amica-financial"]},
    {"name": "Fi Money", "slug_hints": ["fi-money", "fi", "epifi"]},
    {"name": "slice", "slug_hints": ["slice", "garagepreparations"]},
    {"name": "OneCard", "slug_hints": ["onecard", "fpl-technologies"]},
    {"name": "Uni Cards", "slug_hints": ["unicards", "uni-cards"]},
    {"name": "Khatabook", "slug_hints": ["khatabook"]},
    {"name": "OkCredit", "slug_hints": ["okcredit"]},
    {"name": "PolicyBazaar", "slug_hints": ["policybazaar", "pb-fintech"]},
    {"name": "Digit Insurance", "slug_hints": ["godigit", "digit-insurance"]},
    {"name": "Acko", "slug_hints": ["acko", "acko-general-insurance"]},
    {"name": "KreditBee", "slug_hints": ["kreditbee", "finnov"]},
    {"name": "Money View", "slug_hints": ["moneyview", "money-view"]},
    {"name": "Lendingkart", "slug_hints": ["lendingkart"]},
    {"name": "InCred", "slug_hints": ["incred"]},
    {"name": "Turtlemint", "slug_hints": ["turtlemint"]},

    # ── SaaS & Enterprise Software ──
    {"name": "Postman", "slug_hints": ["postman"]},
    {"name": "BrowserStack", "slug_hints": ["browserstack"]},
    {"name": "Hasura", "slug_hints": ["hasura"]},
    {"name": "Chargebee", "slug_hints": ["chargebee"]},
    {"name": "Freshworks", "slug_hints": ["freshworks"]},
    {"name": "Innovaccer", "slug_hints": ["innovaccer"]},
    {"name": "Icertis", "slug_hints": ["icertis"]},
    {"name": "Zenoti", "slug_hints": ["zenoti", "soham-inc"]},
    {"name": "LeadSquared", "slug_hints": ["leadsquared", "marketxcel"]},
    {"name": "HighRadius", "slug_hints": ["highradius"]},
    {"name": "Whatfix", "slug_hints": ["whatfix"]},
    {"name": "Darwinbox", "slug_hints": ["darwinbox"]},
    {"name": "CleverTap", "slug_hints": ["clevertap", "wizrocket"]},
    {"name": "MoEngage", "slug_hints": ["moengage"]},
    {"name": "WebEngage", "slug_hints": ["webengage"]},
    {"name": "Gupshup", "slug_hints": ["gupshup"]},
    {"name": "Yellow.ai", "slug_hints": ["yellowai", "yellow-ai", "yellow-messenger"]},
    {"name": "Sprinklr", "slug_hints": ["sprinklr"]},
    {"name": "Druva", "slug_hints": ["druva"]},
    {"name": "MindTickle", "slug_hints": ["mindtickle"]},
    {"name": "Amagi", "slug_hints": ["amagi"]},
    {"name": "Quizizz", "slug_hints": ["quizizz"]},
    {"name": "Appsmith", "slug_hints": ["appsmith"]},
    {"name": "SigNoz", "slug_hints": ["signoz"]},
    {"name": "Devtron", "slug_hints": ["devtron"]},
    {"name": "Airmeet", "slug_hints": ["airmeet"]},
    {"name": "Wingify", "slug_hints": ["wingify", "vwo"]},

    # ── Edtech ──
    {"name": "upGrad", "slug_hints": ["upgrad"]},
    {"name": "Unacademy", "slug_hints": ["unacademy", "sorting-hat-technologies"]},
    {"name": "Eruditus", "slug_hints": ["eruditus", "emeritus"]},
    {"name": "PhysicsWallah", "slug_hints": ["physicswallah", "pw"]},
    {"name": "Simplilearn", "slug_hints": ["simplilearn"]},
    {"name": "Scaler Academy", "slug_hints": ["scaler", "interviewbit"]},
    {"name": "Masai School", "slug_hints": ["masaischool", "masai-school"]},
    {"name": "Vedantu", "slug_hints": ["vedantu"]},
    {"name": "Cuemath", "slug_hints": ["cuemath"]},
    {"name": "Classplus", "slug_hints": ["classplus", "bunkfit"]},
    {"name": "Teachmint", "slug_hints": ["teachmint"]},
    {"name": "Adda247", "slug_hints": ["adda247"]},
    {"name": "Testbook", "slug_hints": ["testbook"]},

    # ── Logistics, Mobility & AutoTech ──
    {"name": "Delhivery", "slug_hints": ["delhivery"]},
    {"name": "Shadowfax", "slug_hints": ["shadowfax"]},
    {"name": "Shiprocket", "slug_hints": ["shiprocket", "kartrocket"]},
    {"name": "Xpressbees", "slug_hints": ["xpressbees", "busybees-logistics"]},
    {"name": "Blackbuck", "slug_hints": ["blackbuck", "zinka-logistics"]},
    {"name": "Porter", "slug_hints": ["porter", "smartshift-logistics"]},
    {"name": "Ecom Express", "slug_hints": ["ecomexpress", "ecom-express"]},
    {"name": "Rivigo", "slug_hints": ["rivigo"]},
    {"name": "ElasticRun", "slug_hints": ["elasticrun", "elastic-run"]},
    {"name": "Rapido", "slug_hints": ["rapido", "roppen-transportation"]},
    {"name": "Ola", "slug_hints": ["ola", "olacabs", "ani-technologies"]},
    {"name": "Ola Electric", "slug_hints": ["olaelectric", "ola-electric"]},
    {"name": "Ather Energy", "slug_hints": ["atherenergy", "ather-energy"]},
    {"name": "Yulu", "slug_hints": ["yulu", "yulubikes"]},
    {"name": "Bounce", "slug_hints": ["bounce", "bounce-share"]},
    {"name": "BluSmart", "slug_hints": ["blusmart", "blusmart-mobility"]},
    {"name": "Cars24", "slug_hints": ["cars24"]},
    {"name": "Spinny", "slug_hints": ["spinny", "yellow-drive-technologies"]},
    {"name": "CarDekho", "slug_hints": ["cardekho", "girnarsoft"]},

    # ── Travel, Hospitality & Proptech ──
    {"name": "MakeMyTrip", "slug_hints": ["makemytrip", "mmt"]},
    {"name": "ixigo", "slug_hints": ["ixigo", "travenues"]},
    {"name": "Yatra", "slug_hints": ["yatra"]},
    {"name": "EaseMyTrip", "slug_hints": ["easemytrip"]},
    {"name": "OYO", "slug_hints": ["oyo", "oyorooms"]},
    {"name": "NoBroker", "slug_hints": ["nobroker"]},
    {"name": "Magicbricks", "slug_hints": ["magicbricks"]},
    {"name": "Housing.com", "slug_hints": ["housing", "locon-solutions"]},
    {"name": "Square Yards", "slug_hints": ["squareyards", "square-yards"]},

    # ── Healthcare & Healthtech ──
    {"name": "PharmEasy", "slug_hints": ["pharmeasy", "api-holdings"]},
    {"name": "Tata 1mg", "slug_hints": ["1mg", "tata1mg"]},
    {"name": "Practo", "slug_hints": ["practo"]},
    {"name": "MediBuddy", "slug_hints": ["medibuddy", "docsapp"]},
    {"name": "Pristyn Care", "slug_hints": ["pristyncare", "pristyn-care"]},
    {"name": "HealthifyMe", "slug_hints": ["healthifyme"]},
    {"name": "Cult.fit", "slug_hints": ["cultfit", "curefit"]},
    {"name": "Narayana Health", "slug_hints": ["narayanahealth", "narayana-health"]},
    {"name": "Dr. Reddy's", "slug_hints": ["drreddys", "dr-reddys"]},
    {"name": "Cipla", "slug_hints": ["cipla"]},
    {"name": "Sun Pharma", "slug_hints": ["sunpharma", "sun-pharma"]},
    {"name": "Biocon", "slug_hints": ["biocon"]},

    # ── Gaming, Social & Content ──
    {"name": "Dream11", "slug_hints": ["dream11", "dreamsports"]},
    {"name": "Mobile Premier League (MPL)", "slug_hints": ["mpl", "galactus-funware"]},
    {"name": "Games24x7", "slug_hints": ["games24x7", "playgames24x7"]},
    {"name": "WinZO", "slug_hints": ["winzo", "winzogames"]},
    {"name": "Nazara Technologies", "slug_hints": ["nazara"]},
    {"name": "Zupee", "slug_hints": ["zupee"]},
    {"name": "Junglee Games", "slug_hints": ["jungleegames", "junglee-games"]},
    {"name": "Pocket FM", "slug_hints": ["pocketfm", "pocket-fm"]},
    {"name": "Kuku FM", "slug_hints": ["kukufm", "kuku-fm"]},
    {"name": "Pratilipi", "slug_hints": ["pratilipi", "nasadiya-technologies"]},
    {"name": "ShareChat", "slug_hints": ["sharechat", "mohalla-tech"]},
    {"name": "InMobi", "slug_hints": ["inmobi"]},
    {"name": "Glance", "slug_hints": ["glance"]},
    {"name": "Dailyhunt", "slug_hints": ["dailyhunt", "verse-innovation"]},

    # ── IT Services & Digital Engineering ──
    {"name": "Tata Consultancy Services", "slug_hints": ["tcs", "tata-consultancy-services"]},
    {"name": "Infosys", "slug_hints": ["infosys"]},
    {"name": "Wipro", "slug_hints": ["wipro"]},
    {"name": "HCLTech", "slug_hints": ["hcltech", "hcl-technologies"]},
    {"name": "Tech Mahindra", "slug_hints": ["techmahindra", "tech-mahindra"]},
    {"name": "LTIMindtree", "slug_hints": ["ltimindtree", "mindtree"]},
    {"name": "Mphasis", "slug_hints": ["mphasis"]},
    {"name": "Persistent Systems", "slug_hints": ["persistent", "persistent-systems"]},
    {"name": "Coforge", "slug_hints": ["coforge", "niit-technologies"]},
    {"name": "Hexaware", "slug_hints": ["hexaware"]},
    {"name": "Cyient", "slug_hints": ["cyient"]},
    {"name": "Tata Elxsi", "slug_hints": ["tataelxsi", "tata-elxsi"]},
    {"name": "KPIT Technologies", "slug_hints": ["kpit"]},
    {"name": "Birlasoft", "slug_hints": ["birlasoft"]},
    {"name": "Sonata Software", "slug_hints": ["sonatasoftware", "sonata-software"]},
    {"name": "Zensar Technologies", "slug_hints": ["zensar"]},
    {"name": "eClerx", "slug_hints": ["eclerx"]},
    {"name": "Firstsource", "slug_hints": ["firstsource"]},
    {"name": "WNS Global Services", "slug_hints": ["wns", "wnsglobal", "wnsglobalservices"]},
    {"name": "ExlService", "slug_hints": ["exlservice", "exl"]},
    {"name": "Genpact", "slug_hints": ["genpact"]},

    # ── Top MNC Engineering GCCs in India ──
    {"name": "Google", "slug_hints": ["google"]},
    {"name": "Microsoft", "slug_hints": ["microsoft"]},
    {"name": "Amazon", "slug_hints": ["amazon"]},
    {"name": "Meta", "slug_hints": ["meta", "facebook"]},
    {"name": "Apple", "slug_hints": ["apple"]},
    {"name": "Netflix", "slug_hints": ["netflix"]},
    {"name": "Uber", "slug_hints": ["uber"]},
    {"name": "Salesforce", "slug_hints": ["salesforce"]},
    {"name": "Adobe", "slug_hints": ["adobe"]},
    {"name": "Oracle", "slug_hints": ["oracle"]},
    {"name": "Cisco", "slug_hints": ["cisco"]},
    {"name": "Intel", "slug_hints": ["intel"]},
    {"name": "NVIDIA", "slug_hints": ["nvidia"]},
    {"name": "Qualcomm", "slug_hints": ["qualcomm"]},
    {"name": "Intuit", "slug_hints": ["intuit"]},
    {"name": "PayPal", "slug_hints": ["paypal"]},
    {"name": "Stripe", "slug_hints": ["stripe"]},
    {"name": "Airbnb", "slug_hints": ["airbnb"]},
    {"name": "Spotify", "slug_hints": ["spotify"]},
    {"name": "Atlassian", "slug_hints": ["atlassian"]},
    {"name": "Snowflake", "slug_hints": ["snowflake"]},
    {"name": "Databricks", "slug_hints": ["databricks"]},
    {"name": "Twilio", "slug_hints": ["twilio"]},
    {"name": "MongoDB", "slug_hints": ["mongodb"]},
    {"name": "Elastic", "slug_hints": ["elastic"]},
    {"name": "GitHub", "slug_hints": ["github"]},
    {"name": "GitLab", "slug_hints": ["gitlab"]},
    {"name": "Bosch Group", "slug_hints": ["boschgroup", "bosch"]},
    {"name": "Siemens", "slug_hints": ["siemens"]},
    {"name": "Honeywell", "slug_hints": ["honeywell"]},
    {"name": "Schneider Electric", "slug_hints": ["schneiderelectric", "schneider-electric"]},
    {"name": "ABB", "slug_hints": ["abb"]},
    {"name": "Walmart Global Tech", "slug_hints": ["walmart", "walmart-global-tech"]},
    {"name": "Target in India", "slug_hints": ["target"]},
    {"name": "Lowe's India", "slug_hints": ["lowes"]},
    {"name": "JPMorgan Chase", "slug_hints": ["jpmorgan", "jpmorganchase"]},
    {"name": "Goldman Sachs", "slug_hints": ["goldmansachs", "goldman-sachs"]},
    {"name": "Morgan Stanley", "slug_hints": ["morganstanley", "morgan-stanley"]},
    {"name": "Barclays", "slug_hints": ["barclays"]},
    {"name": "Standard Chartered", "slug_hints": ["standardchartered", "standard-chartered"]},
    {"name": "Wells Fargo", "slug_hints": ["wellsfargo", "wells-fargo"]},
    {"name": "Citi", "slug_hints": ["citi", "citigroup"]},
    {"name": "Deutsche Bank", "slug_hints": ["deutschebank", "deutsche-bank"]},
    {"name": "BNY Mellon", "slug_hints": ["bnymellon", "bny-mellon"]},
    {"name": "Fidelity Investments", "slug_hints": ["fidelity"]},
    {"name": "UBS", "slug_hints": ["ubs"]},
    {"name": "American Express", "slug_hints": ["americanexpress", "amex"]},
    {"name": "Visa", "slug_hints": ["visa"]},
    {"name": "Mastercard", "slug_hints": ["mastercard"]},

    # ── Consulting, Audit & Financial Services (Big 4, CA, Finance, HR) ──
    {"name": "Deloitte", "slug_hints": ["deloitte"]},
    {"name": "PwC", "slug_hints": ["pwc", "pricewaterhousecoopers"]},
    {"name": "EY", "slug_hints": ["ey", "ernstandyoung"]},
    {"name": "KPMG", "slug_hints": ["kpmg"]},
    {"name": "McKinsey & Company", "slug_hints": ["mckinsey"]},
    {"name": "Boston Consulting Group", "slug_hints": ["bcg", "bostonconsultinggroup"]},
    {"name": "Bain & Company", "slug_hints": ["bain", "bainandcompany"]},
    {"name": "Kearney", "slug_hints": ["kearney", "atkearney"]},
    {"name": "Oliver Wyman", "slug_hints": ["oliverwyman"]},
    {"name": "Grant Thornton", "slug_hints": ["grantthornton"]},
    {"name": "BDO", "slug_hints": ["bdo", "bdoindia"]},
    {"name": "ICICI Bank", "slug_hints": ["icici", "icicibank"]},
    {"name": "HDFC Bank", "slug_hints": ["hdfc", "hdfcbank"]},
    {"name": "Axis Bank", "slug_hints": ["axisbank", "axis"]},
    {"name": "Kotak Mahindra Bank", "slug_hints": ["kotak", "kotakmahindrabank"]},
    {"name": "Bajaj Finserv", "slug_hints": ["bajajfinserv", "bajaj"]},
    {"name": "Muthoot Finance", "slug_hints": ["muthoot", "muthootfinance"]},
    {"name": "Randstad", "slug_hints": ["randstad", "randstadindia"]},
    {"name": "TeamLease", "slug_hints": ["teamlease", "teamleaseservices"]},
    {"name": "Michael Page", "slug_hints": ["michaelpage", "pagegroup"]},
    {"name": "Kelly Services", "slug_hints": ["kellyservices"]},
]
